# render.yaml (in ROOT)
services:
  - type: web
    name: smart-greenhouse-backend
    runtime: python
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend && gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production